# Generated by Django 4.2.7 on 2023-11-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=40)),
                ('ar_name', models.CharField(max_length=40)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
