# Generated by Django 4.2.7 on 2023-11-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_call', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='ar_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='eng_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auto_call.room'),
            preserve_default=False,
        ),
    ]
