# Generated by Django 4.2.7 on 2023-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_call', '0002_room_rename_ar_name_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emergancy',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
