# Generated by Django 4.2.7 on 2023-11-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_call', '0003_patient_emergancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='log_date',
        ),
    ]
