# Generated by Django 4.2.7 on 2023-12-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_call', '0004_remove_room_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergancy',
            field=models.BooleanField(default=1),
        ),
    ]
